#!/usr/bin/env perl -w

eval 'exec /usr/bin/env perl -w -S $0 ${1+"$@"}'
  if 0;    # not running under some shell

use strict;
use App::Prove;

my $app = App::Prove->new;
$app->process_args(@ARGV);

unless ( $app->run ) {

    # Sound when error
    warn "ERROR!";
    exit;
}

# Sound when success
warn "SUCCESS!";

__END__
