#!/usr/bin/env perl -w

eval 'exec /usr/bin/env perl -w -S $0 ${1+"$@"}'
  if 0;    # not running under some shell

use strict;
use App::Prove;
use Audio::Play::MPG123;

sub playMp3 {
    my ($mp3_file) = @_;

    my $player = Audio::Play::MPG123->new;
    $player->load($mp3_file);
    $player->poll(1) until $player->state == 0;
}

my $app = App::Prove->new;

$app->process_args(@ARGV);

unless ( $app->run ) {

    # Sound when occur some error
    playMp3('/Users/ta_kawakami/Dropbox/curse.mp3');
    exit;
}

# Sound when success
playMp3('/Users/ta_kawakami/Dropbox/level_up.mp3');

__END__
